name: CVE Scanning for Node.js

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'node/package.json'
      - 'node/package-lock.json'
      - 'node/allow-list.json'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prod
        working-directory: node
#       - run: yarn install --production --frozen-lockfile
#         working-directory: node
      - run: npx --yes auditjs ossi --whitelist allow-list.json
        working-directory: node
