name: CVE Scanning for Rust

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'rust/Cargo.toml'
      - '.github/workflows/cve-scanning-rust.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install --force cargo-audit
      - run: cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2020-0159
        working-directory: rust
