# This workflow will scan a .NET project
# For more information see: https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/#dotnet-cli

name: CVE Scanning for .NET

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'dotnet/*.csproj'
      - '.github/workflows/cve-scanning-dotnet.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: dotnet
    - name: Scan
      run: dotnet list package --vulnerable --include-transitive | tee vulnerable.out
      working-directory: dotnet
    - name: Parse result
      run: test `grep -cm 1 'has the following vulnerable packages' vulnerable.out` = 0
      working-directory: dotnet