name: CVE Scanning for Docker

on:
  push:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/cve-scanning-docker.yml'

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f docker/Dockerfile -t user/app:latest docker/
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'docker'
          path: './docker'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
