name: License Scan

on:
  push:
    branches:
      - gradle-license-scanning
  pull_request:
    branches:
      - gradle-license-scanning

jobs:
  license-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'
    - name: Run Gradle License Report
      run: ./gradlew check
