name: License Scanning for Rust

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'rust/Cargo.toml'
      - '.github/workflows/license-scanning-rust.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
      - run: cargo install --force cargo-audit
      - name: Install and run licensebat 
        run: |
          cargo add licensebat-cli
          cargo run licensebat --dependency-file ~/rust/Cargo.lock --licrc-file ~/rust/license.licrc
        working-directory: rust
